enableImmutableInstalls: false

enableProgressBars: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.0.2.cjs

npmScopes:
  dust-defi:
    npmAlwaysAuth: true
    npmAuthToken: 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
    npmRegistryServer: https://npm.pkg.github.com
